-- ════════════════════════════════════════════════════════════
-- DataMEAL Academy — FORMATION DES FORMATEURS (ToF)
-- Gestion Financière des Paysans en Milieu Rural
-- Approche andragogique : partir du vécu, apprendre en faisant
-- Durée : 3 mois (12 semaines) — 12 leçons progressives
-- Public : Formateurs/animateurs ruraux (ToF)
-- ════════════════════════════════════════════════════════════

-- ── Créer le cours ──
INSERT INTO sms_courses (code, title, description, tools, level, total_lessons, order_index, is_published)
VALUES (
  'TOF-FIN-01',
  'Formation des Formateurs : Gestion Financière Paysanne',
  'Parcours de 3 mois pour formateurs ruraux. Apprenez à animer des sessions sur la gestion financière adaptée aux réalités paysannes : budget familial, épargne communautaire, crédit agricole, tontines et planification de campagne. Approche andragogique basée sur le vécu terrain.',
  ARRAY['cahier terrain', 'tableau papier', 'boulier/cailloux', 'images grand format', 'jeu de rôle'],
  'intermediaire',
  12,
  10,
  true
);

-- ══════════════════════════════════════════════════════════
-- MOIS 1 — COMPRENDRE L'ARGENT DU PAYSAN (Semaines 1–4)
-- Objectif : le formateur maîtrise les réalités financières
-- paysannes et sait faire émerger les savoirs du groupe
-- ══════════════════════════════════════════════════════════

-- ── Leçon 1 : Posture du formateur en milieu rural ──
INSERT INTO sms_lessons (course_id, title, type, points, order_index, content)
SELECT id, 'Posture du formateur-animateur en milieu rural', 'notebook', 15, 1,
'{"cells": [
  {"type": "md", "content": "## Vous n''êtes pas un professeur, vous êtes un facilitateur\n\nEn milieu rural, les paysans ont **20, 30, 40 ans d''expérience**. Ils savent déjà beaucoup. Votre rôle n''est pas de leur « enseigner » mais de **faciliter** la prise de conscience et l''organisation de ce qu''ils savent déjà.\n\nC''est le cœur de l''**andragogie** : l''éducation des adultes part de leur vécu, pas d''un manuel."},
  {"type": "callout", "variant": "real", "title": "Le piège du formateur débutant", "content": "Un formateur fraîchement diplômé arrive dans un village avec des PowerPoint et des termes comptables. Les paysans s''ennuient, ne comprennent pas, et ne reviennent pas à la 2e session. Ce qui marche : s''asseoir sous l''arbre à palabres, écouter d''abord, puis poser des questions qui font réfléchir le groupe."},
  {"type": "md", "content": "## Les 5 principes andragogiques (Knowles) adaptés au rural\n\n| Principe | En pratique au village |\n|---|---|\n| **L''adulte a besoin de savoir POURQUOI** | Commencer par un problème concret (« Pourquoi l''argent de la récolte finit avant la prochaine saison ? ») |\n| **L''adulte apporte son expérience** | Faire parler les anciens d''abord, valoriser les savoirs locaux |\n| **L''adulte veut décider lui-même** | Proposer, ne jamais imposer — laisser le groupe choisir ses priorités |\n| **L''adulte apprend pour résoudre un problème immédiat** | Chaque session doit répondre à un problème réel du village |\n| **L''adulte est motivé par des résultats concrets** | Montrer les gains dès la 1ère session (exercice de calcul du budget familial) |"},
  {"type": "md", "content": "## Votre boîte à outils de facilitateur\n\n- **L''arbre à problèmes** : dessiner au sol les causes et conséquences d''un problème financier\n- **Le cercle de parole** : chacun parle à son tour, personne n''est coupé\n- **Les images parlantes** : dessins grand format sans texte, que les participants interprètent\n- **Le jeu de rôle** : simuler une situation (achat à crédit, négociation au marché)\n- **Les cailloux/graines** : pour compter, représenter des montants, faire des parts"},
  {"type": "callout", "variant": "tip", "title": "Règle d''or du facilitateur rural", "content": "Parlez 20% du temps maximum. Les 80% restants, ce sont les participants qui parlent, réfléchissent, calculent et échangent entre eux. Si vous parlez plus que le groupe, vous avez raté votre animation."},
  {"type": "quiz", "question": "Un formateur rural efficace consacre quelle proportion du temps à écouter et faire parler le groupe ?", "opts": ["20% écoute, 80% cours magistral", "50% écoute, 50% cours", "80% écoute et facilitation, 20% apport", "100% cours théorique"], "ans": 2}
]}'::jsonb
FROM sms_courses WHERE code = 'TOF-FIN-01';

-- ── Leçon 2 : D'où vient et où va l'argent du paysan ? ──
INSERT INTO sms_lessons (course_id, title, type, points, order_index, content)
SELECT id, 'D''où vient et où va l''argent du paysan ?', 'notebook', 15, 2,
'{"cells": [
  {"type": "md", "content": "## Activité terrain : la carte des flux d''argent\n\n**Durée** : 2h | **Matériel** : sol sableux ou grande feuille, cailloux de 2 couleurs, bâton\n\nAvant de parler budget, il faut que le groupe **visualise** d''où vient l''argent et où il part. C''est un diagnostic participatif — pas un cours.\n\n### Comment animer cette activité\n\n1. Dessinez un grand cercle au sol : c''est la famille/le ménage\n2. Demandez : « D''où vient l''argent dans votre famille ? » → chaque source = un caillou vert ENTRANT\n3. Demandez : « Où part l''argent ? » → chaque dépense = un caillou rouge SORTANT\n4. Laissez le groupe débattre et compléter"},
  {"type": "callout", "variant": "real", "title": "Ce qui ressort toujours", "content": "Dans 90% des villages d''Afrique de l''Ouest, les paysans identifient : vente de récolte (1-2 fois/an), petit commerce de la femme, travail journalier, transferts de la diaspora. Côté dépenses : nourriture quotidienne, santé, école, cérémonies, intrants agricoles. Le problème fondamental apparaît : les REVENUS sont saisonniers mais les DÉPENSES sont permanentes."},
  {"type": "md", "content": "## Les 4 sources de revenus typiques du paysan\n\n| Source | Fréquence | Caractéristique |\n|---|---|---|\n| **Vente de récolte** | 1-2x par an | Gros montant, d''un coup |\n| **Petit commerce** | Quotidien/hebdomadaire | Petits montants réguliers |\n| **Travail journalier** | Saisonnier | Variable, imprévisible |\n| **Transferts (diaspora/famille)** | Irrégulier | Non contrôlable |\n\n## Les 5 postes de dépenses incontournables\n\n1. **Alimentation** (50-70% du budget !)\n2. **Santé** (imprévisible, souvent catastrophique)\n3. **Scolarité** (concentrée en septembre-octobre)\n4. **Intrants agricoles** (semences, engrais — en début de saison)\n5. **Cérémonies sociales** (mariages, funérailles, baptêmes)"},
  {"type": "embed", "title": "Notebook live : visualiser le déséquilibre saisonnier", "code": "mois = [''Jan'',''Fev'',''Mar'',''Avr'',''Mai'',''Jun'',''Jul'',''Aou'',''Sep'',''Oct'',''Nov'',''Dec'']\nrevenus =  [20, 15, 10, 10, 5, 5, 5, 5, 10, 80, 150, 100]  # pic a la recolte\ndepenses = [35, 35, 40, 45, 50, 50, 45, 40, 60, 50, 40, 35]  # quasi constantes\nprint(\"Mois     Revenus  Depenses  Solde\")\nprint(\"-\" * 38)\ncumul = 0\nfor m, r, d in zip(mois, revenus, depenses):\n    solde = r - d\n    cumul += solde\n    indicateur = \"<<< DEFICIT\" if solde < 0 else \"\"\n    print(f\"{m:4}  {r:>8,}  {d:>8,}  {solde:>+6,}  {indicateur}\")\nprint(f\"\\nTotal annuel : revenus {sum(revenus):,} | depenses {sum(depenses):,}\")\nprint(f\"Le paysan survit mais traverse 7 mois de deficit !\")\n"},
  {"type": "callout", "variant": "tip", "title": "Guide de facilitation", "content": "Après l''activité des cailloux, posez LA question clé : « Regardez bien — il y a plus de cailloux qui entrent ou qui sortent ? » Laissez le silence. Le groupe va lui-même identifier le déséquilibre. C''est BEAUCOUP plus puissant que si vous le dites vous-même."},
  {"type": "quiz", "question": "Quel est le problème financier fondamental du paysan que l''activité des cailloux fait apparaître ?", "opts": ["Il ne gagne pas assez", "Ses revenus sont saisonniers mais ses dépenses sont permanentes", "Il dépense trop en cérémonies", "Il ne sait pas compter"], "ans": 1}
]}'::jsonb
FROM sms_courses WHERE code = 'TOF-FIN-01';

-- ── Leçon 3 : Construire un budget familial paysan ──
INSERT INTO sms_lessons (course_id, title, type, points, order_index, content)
SELECT id, 'Construire un budget familial avec les paysans', 'notebook', 20, 3,
'{"cells": [
  {"type": "md", "content": "## L''outil central : le budget en tas de graines\n\n**Durée** : 3h | **Matériel** : graines (maïs, haricots), 12 petits tas de sable ou cuvettes (= 12 mois), feuille A3\n\nLe budget n''est pas un tableau Excel — c''est un **outil de décision**. Avec des paysans qui ne lisent pas toujours, on utilise des graines pour représenter l''argent.\n\n### Déroulement de l''animation\n\n1. Disposez 12 tas de sable en ligne (= janvier à décembre)\n2. Donnez 100 graines de maïs au participant : « Voici tout l''argent que vous gagnez en un an »\n3. Demandez : « Répartissez ces graines dans les mois où vous recevez de l''argent »\n4. Donnez 100 graines de haricots : « Maintenant, répartissez vos dépenses par mois »\n5. Le participant VOIT les mois où les haricots dépassent le maïs = les mois de galère"},
  {"type": "callout", "variant": "real", "title": "Témoignage d''un animateur au Mali", "content": "« Quand Mamadou a vu que pendant 7 mois sur 12, il avait plus de haricots (dépenses) que de maïs (revenus), il a dit : ''Ah, c''est pour ça qu''on souffre de mars à septembre !'' Il le vivait chaque année mais ne l''avait jamais VU. » — Animateur GRAAP, Sikasso"},
  {"type": "md", "content": "## Du tas de graines au tableau simplifié\n\nUne fois la prise de conscience faite, accompagnez ceux qui le souhaitent vers un **tableau papier simplifié** :\n\n| Mois | Ce qui rentre | Ce qui sort | Il reste |\n|---|---|---|---|\n| Janvier | 20 000 | 35 000 | -15 000 |\n| Février | 15 000 | 35 000 | -20 000 |\n| ... | ... | ... | ... |\n| Novembre | 150 000 | 40 000 | +110 000 |\n\nUtilisez la monnaie locale (FCFA, Ariary, etc.). Les montants viennent DU PAYSAN, pas de vous."},
  {"type": "embed", "title": "Notebook live : simuler un budget paysan annuel", "code": "# Budget type d''un menage paysan (coton + petit commerce, zone soudanienne)\nmois = [''Jan'',''Fev'',''Mar'',''Avr'',''Mai'',''Jun'',''Jul'',''Aou'',''Sep'',''Oct'',''Nov'',''Dec'']\nentrees = [20000, 15000, 10000, 10000, 5000, 5000, 5000, 5000, 10000, 80000, 150000, 100000]\nsorties = [35000, 35000, 40000, 45000, 50000, 50000, 45000, 40000, 60000, 50000, 40000, 35000]\n\nprint(\"BUDGET FAMILIAL PAYSAN (FCFA)\")\nprint(f\"{'Mois':>4} {'Entrees':>10} {'Sorties':>10} {'Solde':>10} {'Cumul':>10}\")\nprint(\"-\" * 48)\ncumul = 0\nfor m, e, s in zip(mois, entrees, sorties):\n    solde = e - s\n    cumul += solde\n    alerte = \" !!\" if cumul < 0 else \"\"\n    print(f\"{m:>4} {e:>10,} {s:>10,} {solde:>+10,} {cumul:>+10,}{alerte}\")\nprint(f\"\\nMois en deficit : {sum(1 for e,s in zip(entrees,sorties) if e < s)} sur 12\")\nprint(f\"Epargne possible (mois positifs) : {sum(e-s for e,s in zip(entrees,sorties) if e > s):,} FCFA\")\n"},
  {"type": "md", "content": "## Ce que le formateur doit faire APRÈS l''exercice\n\n1. **Valoriser** : « Vous venez de créer votre premier budget ! »\n2. **Questionner** : « Que pouvez-vous faire pour ces mois difficiles ? »\n3. **Ne PAS donner la réponse** : laisser le groupe proposer (stocker du grain, tontine, petit commerce de contre-saison...)\n4. **Programmer** : « La prochaine session, on va explorer une de vos solutions : l''épargne »"},
  {"type": "quiz", "question": "Pourquoi utiliser des graines plutôt qu''un tableau écrit pour le budget ?", "opts": ["C''est moins cher", "Ça permet aux personnes non-alphabétisées de participer pleinement et de VOIR le déséquilibre", "Les graines sont plus jolies", "C''est obligatoire"], "ans": 1}
]}'::jsonb
FROM sms_courses WHERE code = 'TOF-FIN-01';

-- ── Leçon 4 : L'épargne paysanne et la tontine ──
INSERT INTO sms_lessons (course_id, title, type, points, order_index, content)
SELECT id, 'L''épargne paysanne : tontines, AVEC et stratégies locales', 'notebook', 20, 4,
'{"cells": [
  {"type": "md", "content": "## Les paysans épargnent DÉJÀ — mais comment ?\n\n**Durée** : 2h30 | **Matériel** : dessins grand format (grenier, tontine, banque, téléphone), graines\n\n### Activité d''ouverture : « Où gardez-vous votre argent ? »\n\nFaites un tour de cercle. Les réponses typiques :\n- Sous le matelas / dans un pot enterré\n- Dans le grenier (stock de grain = épargne en nature)\n- Chez un parent de confiance\n- Dans la tontine du village\n- Au téléphone (mobile money)\n- À la banque (rare en zone rurale)\n\nÉcrivez ou dessinez chaque réponse. Puis demandez : « Quels sont les avantages et les risques de chacun ? »"},
  {"type": "callout", "variant": "real", "title": "Le grenier = un compte d''épargne", "content": "En zone sahélienne, stocker 5 sacs de mil après la récolte plutôt que tout vendre, c''est une stratégie d''épargne en nature. Le mil acheté à 250 FCFA/kg en novembre se revend 400 FCFA/kg en juillet. C''est un ''rendement'' de 60% ! Les paysans le font depuis des générations. Le formateur doit VALORISER cette intelligence, pas la remplacer."},
  {"type": "md", "content": "## La tontine : le système financier du village\n\nLa **tontine** (ou ROSCA) est le système d''épargne-crédit le plus répandu en Afrique rurale. Principe :\n\n- 10 membres cotisent 5 000 FCFA/semaine\n- Chaque semaine, UN membre reçoit la cagnotte (50 000 FCFA)\n- Au bout de 10 semaines, tout le monde a reçu une fois\n\n### Les variantes à connaître\n\n| Type | Fonctionnement | Avantage |\n|---|---|---|\n| **Tontine simple** | Tour fixe | Prévisible, simple |\n| **Tontine enchères** | Le plus offrant reçoit | Flexibilité (urgences) |\n| **AVEC/VSLA** | Épargne + crédit + fonds social | Structure complète, fonds d''urgence |"},
  {"type": "embed", "title": "Notebook live : simuler une tontine de 10 membres", "code": "membres = [f\"Membre_{i+1}\" for i in range(10)]\ncotisation = 5000  # FCFA par semaine\ncagnotte = cotisation * len(membres)\n\nprint(\"SIMULATION TONTINE VILLAGEOISE\")\nprint(f\"Membres : {len(membres)} | Cotisation : {cotisation:,} FCFA/semaine\")\nprint(f\"Cagnotte hebdomadaire : {cagnotte:,} FCFA\\n\")\n\nfor semaine, beneficiaire in enumerate(membres, 1):\n    epargne_nette = cotisation * (len(membres) - semaine)\n    print(f\"Semaine {semaine:>2} : {beneficiaire} recoit {cagnotte:,} FCFA\"\n          f\"  (a cotise {cotisation * semaine:,}, reste a cotiser {epargne_nette:,})\")\n\nprint(f\"\\nTotal mobilise en 10 semaines : {cagnotte * len(membres):,} FCFA\")\nprint(\"Chaque membre a epargne ET recu exactement la meme somme.\")\n"},
  {"type": "md", "content": "## Guide de facilitation : l''exercice de la tontine simulée\n\nOrganisez une **vraie simulation** avec le groupe :\n1. 10 volontaires se mettent en cercle\n2. Chacun a 10 graines (= sa cotisation)\n3. À chaque tour, chacun donne 1 graine au bénéficiaire\n4. Le bénéficiaire reçoit 10 graines d''un coup\n5. Après 10 tours : tout le monde a donné 10 et reçu 10\n\nQuestion de facilitation : « Alors, à quoi sert la tontine si on reçoit exactement ce qu''on donne ? »\n\n**Réponse attendue du groupe** : « Elle FORCE l''épargne et donne un GROS montant d''un coup, qu''on n''aurait jamais réussi à accumuler seul. »"},
  {"type": "quiz", "question": "Quel est le principal avantage de la tontine pour un paysan ?", "opts": ["Elle rapporte des intérêts", "Elle force l''épargne régulière et donne un gros montant d''un coup", "Elle remplace la banque", "Elle est gratuite"], "ans": 1}
]}'::jsonb
FROM sms_courses WHERE code = 'TOF-FIN-01';

-- ══════════════════════════════════════════════════════════
-- MOIS 2 — GÉRER ET PLANIFIER (Semaines 5–8)
-- Objectif : le formateur sait animer des exercices pratiques
-- de planification financière agricole
-- ══════════════════════════════════════════════════════════

-- ── Leçon 5 : Le coût de production agricole ──
INSERT INTO sms_lessons (course_id, title, type, points, order_index, content)
SELECT id, 'Calculer le coût de production avec les paysans', 'notebook', 20, 5,
'{"cells": [
  {"type": "md", "content": "## Le paysan connaît-il le vrai coût de sa production ?\n\n**Durée** : 3h | **Matériel** : grande feuille, graines, dessins (champ, sac d''engrais, houe, main-d''œuvre)\n\nDans 80% des cas, le paysan ne connaît PAS le coût total de production de son champ. Il voit l''argent dépensé pour l''engrais et les semences, mais oublie la main-d''œuvre familiale, le transport, le stockage.\n\n### Animation : « Combien vous coûte un sac de maïs ? »\n\n1. Dessinez un grand champ au tableau/sol\n2. Demandez : « Pour cultiver 1 hectare de maïs, qu''est-ce qu''il vous faut ? »\n3. Le groupe liste : semences, engrais, labour, sarclage, récolte, transport...\n4. Pour CHAQUE élément : « Combien ça coûte ? » (en FCFA)\n5. Additionnez ensemble. La surprise est souvent énorme."},
  {"type": "callout", "variant": "real", "title": "Le choc du calcul", "content": "Dans un village du nord-Cameroun, un paysan vendait son sac de maïs à 8 000 FCFA en pensant faire du bénéfice. Quand le groupe a calculé tous les coûts (y compris la main-d''œuvre familiale valorisée), le coût de production était de 9 500 FCFA par sac. Il travaillait à PERTE depuis des années sans le savoir."},
  {"type": "embed", "title": "Notebook live : calcul du coût de production (1 ha maïs)", "code": "print(\"COUT DE PRODUCTION — 1 hectare de mais (zone soudanienne)\")\nprint(\"=\" * 55)\n\ncouts = [\n    (\"Semences (20 kg)\", 15000),\n    (\"Engrais NPK (2 sacs)\", 40000),\n    (\"Engrais uree (1 sac)\", 22000),\n    (\"Labour (tracteur ou attelage)\", 25000),\n    (\"Semis (main-d oeuvre)\", 10000),\n    (\"1er sarclage (main-d oeuvre)\", 15000),\n    (\"2e sarclage (main-d oeuvre)\", 12000),\n    (\"Recolte (main-d oeuvre)\", 20000),\n    (\"Transport champ-maison\", 8000),\n    (\"Sacs de stockage\", 5000),\n    (\"Produit de conservation\", 3000),\n]\ntotal = 0\nfor poste, montant in couts:\n    total += montant\n    print(f\"  {poste:<35} {montant:>8,} FCFA\")\nprint(\"-\" * 55)\nprint(f\"  {'COUT TOTAL':.<35} {total:>8,} FCFA\")\n\nrendement_sacs = 20  # sacs de 100 kg par hectare\ncout_par_sac = total // rendement_sacs\nprint(f\"\\nRendement moyen : {rendement_sacs} sacs/ha\")\nprint(f\"Cout par sac : {cout_par_sac:,} FCFA\")\nprint(f\"\\nSi prix de vente = 8 000 FCFA/sac : {'PERTE' if 8000 < cout_par_sac else 'BENEFICE'}\")\nprint(f\"Si prix de vente = 12 000 FCFA/sac : benefice de {12000 - cout_par_sac:,} FCFA/sac\")\n"},
  {"type": "md", "content": "## La main-d''œuvre familiale : le coût invisible\n\nLe piège classique : le paysan dit « le sarclage ne me coûte rien, c''est ma femme et mes enfants ». Posez la question : « Si votre femme allait vendre au marché au lieu de sarcler, combien gagnerait-elle ? »\n\nC''est le **coût d''opportunité**. Sans ce concept (qu''on explique sans jargon), le paysan ne peut pas prendre de bonnes décisions."},
  {"type": "callout", "variant": "tip", "title": "Technique de facilitation : le prix plancher", "content": "Une fois le coût de production calculé, aidez le groupe à définir un PRIX PLANCHER de vente : le prix en dessous duquel il ne faut JAMAIS vendre. C''est un outil de négociation puissant au marché. Écrivez-le sur un carton que le paysan garde dans sa poche."},
  {"type": "quiz", "question": "Un paysan vend son sac de maïs à 8 000 FCFA. Le coût total de production est de 9 500 FCFA/sac. Quelle est la situation ?", "opts": ["Il fait un bénéfice de 1 500 FCFA", "Il travaille à perte de 1 500 FCFA par sac", "Il est à l''équilibre", "Impossible à dire"], "ans": 1}
]}'::jsonb
FROM sms_courses WHERE code = 'TOF-FIN-01';

-- ── Leçon 6 : Planifier la campagne agricole ──
INSERT INTO sms_lessons (course_id, title, type, points, order_index, content)
SELECT id, 'Planifier financièrement la campagne agricole', 'notebook', 20, 6,
'{"cells": [
  {"type": "md", "content": "## Le calendrier cultural = le calendrier financier\n\n**Durée** : 3h | **Matériel** : corde de 3 mètres, 12 nœuds (= 12 mois), cartons illustrés des activités\n\n### Activité : La corde des saisons\n\n1. Tendez une corde avec 12 nœuds (1 par mois) entre deux piquets\n2. Demandez au groupe de placer les cartons sur les bons mois : labour, semis, sarclage, récolte, vente\n3. Sous chaque carton, placez des graines = l''argent nécessaire à ce moment\n4. Question clé : « En avril quand il faut acheter les semences et l''engrais, est-ce que vous avez l''argent ? »"},
  {"type": "callout", "variant": "real", "title": "Le cercle vicieux du crédit de campagne", "content": "En avril, le paysan n''a plus d''argent (il a tout dépensé depuis la récolte de novembre). Il emprunte à un commerçant : semences + engrais à crédit, remboursable en nature à la récolte, au prix de novembre (le plus bas). Résultat : il perd 30 à 50% de la valeur de sa production. Chaque année, le même piège. La planification financière brise ce cycle."},
  {"type": "embed", "title": "Notebook live : calendrier cultural et besoins de trésorerie", "code": "mois = [''Jan'',''Fev'',''Mar'',''Avr'',''Mai'',''Jun'',''Jul'',''Aou'',''Sep'',''Oct'',''Nov'',''Dec'']\nactivites = [\n    ''Repos'', ''Defrichage'', ''Preparation'', ''SEMIS+INTRANTS'',\n    ''Sarclage 1'', ''Sarclage 2'', ''Entretien'', ''Epiaison'',\n    ''Pre-recolte'', ''RECOLTE'', ''VENTE pic'', ''Vente/Stockage''\n]\nbesoins_fcfa = [0, 5000, 15000, 80000, 15000, 12000, 5000, 0, 0, 20000, 5000, 5000]\nrentrees_fcfa = [0, 0, 0, 0, 0, 0, 0, 0, 0, 30000, 150000, 80000]\n\nprint(\"CALENDRIER CULTURAL ET TRESORERIE (mais, 1 ha)\")\nprint(f\"{'Mois':>4} {'Activite':<18} {'Besoins':>10} {'Rentrees':>10} {'Solde':>10}\")\nprint(\"-\" * 56)\ncumul = 0\nfor m, a, b, r in zip(mois, activites, besoins_fcfa, rentrees_fcfa):\n    solde = r - b\n    cumul += solde\n    alerte = \" <<<\" if cumul < -30000 else \"\"\n    print(f\"{m:>4} {a:<18} {b:>10,} {r:>10,} {cumul:>+10,}{alerte}\")\nprint(f\"\\nBesoin de tresorerie maximum : {abs(min(0, *[sum(r-b for r,b in zip(rentrees_fcfa[:i+1], besoins_fcfa[:i+1])) for i in range(12)])):,} FCFA\")\nprint(\"C est le montant a epargner ou emprunter AVANT la campagne\")\n"},
  {"type": "md", "content": "## La stratégie de l''épargne anticipée\n\nLe formateur aide le groupe à calculer combien mettre de côté chaque mois APRÈS la récolte pour couvrir les besoins d''avril :\n\n- Besoins en intrants (avril) : ~80 000 FCFA\n- Mois disponibles pour épargner (nov → mars) : 5 mois\n- Épargne mensuelle nécessaire : 80 000 ÷ 5 = **16 000 FCFA/mois**\n\nC''est concret, atteignable, et ça casse le cycle de l''endettement."},
  {"type": "callout", "variant": "tip", "title": "L''exercice à faire à la maison", "content": "Demandez à chaque participant de rentrer chez lui et de calculer, avec sa femme/son mari, combien il lui faut pour la prochaine campagne. Prochaine session : chacun revient avec son chiffre. C''est l''apprentissage par l''action — le cœur de l''andragogie."},
  {"type": "quiz", "question": "Pourquoi le paysan s''endette-t-il souvent en avril ?", "opts": ["Parce qu''il est paresseux", "Parce qu''il n''a pas planifié l''épargne des revenus de la récolte pour couvrir les intrants", "Parce que les intrants sont trop chers", "Parce que la banque le force"], "ans": 1}
]}'::jsonb
FROM sms_courses WHERE code = 'TOF-FIN-01';

-- ── Leçon 7 : Le crédit agricole — opportunité ou piège ? ──
INSERT INTO sms_lessons (course_id, title, type, points, order_index, content)
SELECT id, 'Le crédit agricole : opportunité ou piège ?', 'notebook', 20, 7,
'{"cells": [
  {"type": "md", "content": "## Jeu de rôle : le paysan face au crédit\n\n**Durée** : 2h30 | **Matériel** : 3 chaises (3 rôles), cartons avec les offres de crédit\n\n### Scénario du jeu de rôle\n\nAminata a besoin de 100 000 FCFA pour acheter des intrants. Trois personnes lui proposent un crédit :\n\n- **Le commerçant** : « Je te donne les intrants maintenant, tu me rembourses 5 sacs de maïs à la récolte » (valeur : 150 000 FCFA → taux effectif ~50%)\n- **La microfinance** : « 100 000 FCFA à 2% par mois sur 8 mois » (taux effectif ~19%)\n- **L''AVEC/VSLA** : « 100 000 FCFA à 5% sur 4 mois, remboursement flexible » (taux effectif ~5%)\n\n3 volontaires jouent les rôles. Aminata (un 4e volontaire) doit choisir."},
  {"type": "callout", "variant": "warning", "title": "Le piège du crédit en nature", "content": "Le crédit du commerçant est le plus CHER mais le plus FACILE d''accès. Pas de papier, pas de garantie. C''est pour ça que 70% des paysans le choisissent. Le rôle du formateur est de rendre VISIBLE le coût caché, pas de juger."},
  {"type": "embed", "title": "Notebook live : comparer les 3 options de crédit", "code": "print(\"COMPARAISON DES 3 OPTIONS DE CREDIT (100 000 FCFA)\")\nprint(\"=\" * 60)\n\noptions = [\n    {\"nom\": \"Commercant (intrants a credit)\",\n     \"rembourse\": 150000, \"duree\": \"4 mois\", \"cout\": 50000, \"taux\": 50},\n    {\"nom\": \"Microfinance (2%/mois, 8 mois)\",\n     \"rembourse\": 119000, \"duree\": \"8 mois\", \"cout\": 19000, \"taux\": 19},\n    {\"nom\": \"AVEC/VSLA (5% sur 4 mois)\",\n     \"rembourse\": 105000, \"duree\": \"4 mois\", \"cout\": 5000, \"taux\": 5},\n]\nfor o in options:\n    print(f\"\\n  {o['nom']}\")\n    print(f\"    Montant rembourse : {o['rembourse']:>10,} FCFA\")\n    print(f\"    Cout du credit    : {o['cout']:>10,} FCFA\")\n    print(f\"    Taux effectif     : {o['taux']:>9}%\")\n    print(f\"    Duree             : {o['duree']}\")\n\necart = options[0][\"cout\"] - options[2][\"cout\"]\nprint(f\"\\nDifference entre le plus cher et le moins cher : {ecart:,} FCFA\")\nprint(f\"Soit {ecart // 5000} semaines de cotisation tontine economisees !\")\n"},
  {"type": "md", "content": "## Les 3 règles d''or du crédit agricole\n\nAprès le jeu de rôle et le calcul, faites émerger ces règles du groupe :\n\n1. **Emprunter UNIQUEMENT pour un investissement productif** (intrants, équipement) — jamais pour les cérémonies ou la consommation\n2. **Toujours calculer le coût TOTAL du remboursement** avant de signer\n3. **Préférer l''épargne au crédit** quand c''est possible (leçon 4 + leçon 6)"},
  {"type": "callout", "variant": "tip", "title": "Facilitation : pas de jugement", "content": "Si un participant dit ''moi j''emprunte toujours au commerçant'', ne le critiquez pas. Demandez : ''Combien tu lui rembourses ?'' et laissez le groupe calculer. Le jugement vient du groupe, pas du formateur. C''est ça, l''andragogie."},
  {"type": "quiz", "question": "Un commerçant prête 100 000 FCFA en intrants et demande 5 sacs de maïs à 30 000 FCFA le sac en retour. Quel est le coût du crédit ?", "opts": ["0 FCFA, c''est un échange", "50 000 FCFA (150 000 remboursé - 100 000 emprunté)", "30 000 FCFA", "100 000 FCFA"], "ans": 1}
]}'::jsonb
FROM sms_courses WHERE code = 'TOF-FIN-01';

-- ── Leçon 8 : Vendre au bon moment ──
INSERT INTO sms_lessons (course_id, title, type, points, order_index, content)
SELECT id, 'Stratégies de commercialisation : vendre au bon moment', 'notebook', 20, 8,
'{"cells": [
  {"type": "md", "content": "## Le paradoxe du paysan : il vend quand le prix est le plus bas\n\n**Durée** : 2h30 | **Matériel** : courbe des prix dessinée au sol (12 mois), graines\n\n### Activité : La courbe des prix au sol\n\n1. Tracez une ligne de 3 mètres au sol (= 12 mois, janvier à décembre)\n2. Demandez au groupe : « En novembre, un sac de maïs coûte combien au marché ? Et en juillet ? »\n3. Empilez des cailloux pour représenter le prix de chaque mois\n4. Le groupe VOIT la courbe : prix bas à la récolte, prix haut en soudure\n5. Question : « Vous vendez à quel moment ? » → « À la récolte... » → « Quand le prix est le plus bas ! »"},
  {"type": "callout", "variant": "real", "title": "Le warrantage : la solution qui change la donne", "content": "Au Niger, le projet P4P du PAM a introduit le warrantage : les paysans stockent leur grain dans un entrepôt certifié, reçoivent un crédit de 70% de la valeur immédiate, et vendent 4-6 mois plus tard quand les prix ont monté de 50-80%. Résultat : +40% de revenus en moyenne pour les paysans participants."},
  {"type": "embed", "title": "Notebook live : gain du stockage et vente différée", "code": "mois = [''Nov'',''Dec'',''Jan'',''Fev'',''Mar'',''Avr'',''Mai'',''Jun'',''Jul'']\nprix_sac = [8000, 8500, 9500, 11000, 13000, 15000, 17000, 19000, 20000]\n\nprint(\"EVOLUTION DU PRIX D UN SAC DE MAIS (FCFA)\")\nprint(\"-\" * 45)\nfor m, p in zip(mois, prix_sac):\n    barre = \"#\" * (p // 1000)\n    print(f\"{m:>4} {p:>7,} FCFA  {barre}\")\n\nproduction = 20  # sacs\nvente_immediate = production * prix_sac[0]\nvente_differee = production * prix_sac[6]  # vente en mai\ngain = vente_differee - vente_immediate\n\nprint(f\"\\n--- SCENARIO : 20 sacs ---\")\nprint(f\"Vente immediate (novembre) : {vente_immediate:>10,} FCFA\")\nprint(f\"Vente differee (mai)       : {vente_differee:>10,} FCFA\")\nprint(f\"GAIN du stockage           : {gain:>+10,} FCFA ({gain*100//vente_immediate}%)\")\nprint(f\"\\nCout de stockage estime    : {15000:>10,} FCFA\")\nprint(f\"Gain NET                   : {gain - 15000:>+10,} FCFA\")\n"},
  {"type": "md", "content": "## Les 4 stratégies de commercialisation à enseigner\n\n| Stratégie | Principe | Pour qui |\n|---|---|---|\n| **Vente groupée** | Vendre ensemble = meilleur prix de négociation | Coopératives |\n| **Stockage individuel** | Garder et vendre en mai-juillet | Paysans avec grenier sec |\n| **Warrantage** | Stocker + crédit à 70% + vendre plus tard | Avec un entrepôt certifié |\n| **Transformation** | Farine, huile → valeur ajoutée | Groupements féminins |\n\nLe formateur ne prescrit pas UNE stratégie. Il les présente et le groupe choisit selon son contexte."},
  {"type": "quiz", "question": "Un paysan vend 20 sacs à 8 000 FCFA en novembre au lieu de 17 000 FCFA en mai. Combien perd-il ?", "opts": ["Rien, il a vendu", "90 000 FCFA", "180 000 FCFA (différence de 9 000 FCFA × 20 sacs)", "20 000 FCFA"], "ans": 2}
]}'::jsonb
FROM sms_courses WHERE code = 'TOF-FIN-01';

-- ══════════════════════════════════════════════════════════
-- MOIS 3 — TRANSMETTRE ET PÉRENNISER (Semaines 9–12)
-- Objectif : le formateur sait structurer une session,
-- évaluer les apprentissages, et former d'autres formateurs
-- ══════════════════════════════════════════════════════════

-- ── Leçon 9 : Gérer les risques financiers ──
INSERT INTO sms_lessons (course_id, title, type, points, order_index, content)
SELECT id, 'Gérer les risques : maladies, sécheresse, vol', 'notebook', 20, 9,
'{"cells": [
  {"type": "md", "content": "## Les risques qui ruinent les paysans\n\n**Durée** : 2h30 | **Matériel** : cartes illustrées des risques, graines, 3 boîtes (prévention, atténuation, transfert)\n\n### Activité : le classement des risques\n\n1. Distribuez des cartes illustrées : sécheresse, inondation, maladie de la famille, maladie des cultures, vol, décès d''un bœuf, chute des prix, incendie du grenier\n2. Le groupe classe les risques : « Quel est le PLUS fréquent ? Le plus GRAVE ? »\n3. Pour chaque risque, demandez : « Est-ce qu''on peut l''éviter ? Le réduire ? Le partager ? »"},
  {"type": "callout", "variant": "real", "title": "L''histoire de Moussa", "content": "Moussa, agriculteur au Burkina Faso, avait économisé 200 000 FCFA pour acheter un bœuf de trait. Son fils est tombé malade du paludisme. En une semaine, toute l''épargne a été dépensée en soins médicaux. Plus de bœuf, campagne ratée. Sans fonds d''urgence séparé, UN événement peut effacer des ANNÉES d''efforts."},
  {"type": "md", "content": "## Les 3 stratégies de gestion des risques\n\n| Stratégie | Exemple concret | Coût |\n|---|---|---|\n| **Prévenir** | Diversifier les cultures, variétés résistantes | Faible |\n| **Atténuer** | Fonds d''urgence (= épargne séparée pour les coups durs) | Moyen |\n| **Transférer** | Assurance récolte, mutuelle de santé, fonds social de l''AVEC | Variable |\n\n### Le fonds d''urgence : la priorité n°1\n\nAvant même d''épargner pour les intrants, chaque ménage devrait constituer un **fonds d''urgence** équivalent à 2-3 mois de dépenses alimentaires. C''est le matelas qui empêche de basculer."},
  {"type": "embed", "title": "Notebook live : impact d''un choc AVEC et SANS fonds d''urgence", "code": "print(\"SCENARIO : maladie grave dans la famille\")\nprint(\"Cout des soins : 150 000 FCFA\\n\")\n\nprint(\"--- SANS fonds d urgence ---\")\nepargne_intrants = 80000\nprint(f\"Epargne intrants disponible : {epargne_intrants:,} FCFA\")\nprint(f\"Le paysan utilise son epargne intrants : -{epargne_intrants:,}\")\nreste_a_payer = 150000 - epargne_intrants\nprint(f\"Reste a payer : {reste_a_payer:,} FCFA -> emprunt au commercant\")\nprint(f\"Consequence : pas d intrants -> campagne ratee -> dette\")\nprint(f\"Perte estimee sur l annee : ~300 000 FCFA\\n\")\n\nprint(\"--- AVEC fonds d urgence de 150 000 FCFA ---\")\nfonds_urgence = 150000\nprint(f\"Fonds d urgence : {fonds_urgence:,} FCFA\")\nprint(f\"Soins payes par le fonds : -{150000:,}\")\nprint(f\"Epargne intrants INTACTE : {epargne_intrants:,} FCFA\")\nprint(f\"Campagne normale -> revenus normaux\")\nprint(f\"\\nDifference : ~300 000 FCFA de revenus preserves\")\nprint(f\"Le fonds d urgence a RAPPORTE 300 000 FCFA !\")\n"},
  {"type": "callout", "variant": "tip", "title": "Facilitation : les 3 boîtes", "content": "Apportez 3 boîtes étiquetées : INTRANTS, URGENCE, FAMILLE. Avec des graines, montrez au groupe comment répartir les revenus de la récolte dans 3 enveloppes différentes. C''est la méthode des enveloppes — simple, visuelle, applicable immédiatement."},
  {"type": "quiz", "question": "Pourquoi le fonds d''urgence doit-il être SÉPARÉ de l''épargne pour les intrants ?", "opts": ["Pour compliquer les choses", "Pour éviter qu''un imprévu détruise la campagne agricole en entamant l''épargne productive", "Pour gagner plus d''intérêts", "Ce n''est pas nécessaire"], "ans": 1}
]}'::jsonb
FROM sms_courses WHERE code = 'TOF-FIN-01';

-- ── Leçon 10 : Structurer une session de formation ──
INSERT INTO sms_lessons (course_id, title, type, points, order_index, content)
SELECT id, 'Structurer et animer une session de formation au village', 'notebook', 25, 10,
'{"cells": [
  {"type": "md", "content": "## Le plan de session APCA : le canevas du formateur rural\n\nChaque session que vous animez au village doit suivre le cycle **APCA** :\n\n1. **A**ccroche (15 min) — Un problème vécu, une histoire, une question provocante\n2. **P**ratique (60 min) — Activité participative (cailloux, jeu de rôle, calcul collectif)\n3. **C**onceptualisation (20 min) — Le groupe formule la leçon apprise (PAS le formateur)\n4. **A**ction (15 min) — Engagement concret à appliquer avant la prochaine session\n\nDurée totale : **2h maximum**. Au-delà, les adultes en milieu rural décrochent (ils ont des champs à cultiver)."},
  {"type": "callout", "variant": "real", "title": "Pourquoi APCA et pas un cours classique ?", "content": "La recherche en andragogie (Kolb, Knowles, Freire) montre que les adultes retiennent 20% de ce qu''ils entendent, 50% de ce qu''ils voient, mais 80% de ce qu''ils FONT. Le cycle APCA met la PRATIQUE au centre. Le formateur parle 20% du temps, le groupe fait 80%."},
  {"type": "md", "content": "## Exemple : session sur le budget familial\n\n| Phase | Durée | Le formateur fait | Les participants font |\n|---|---|---|---|\n| **Accroche** | 15 min | Raconte l''histoire de Mamadou qui n''a plus d''argent en mars | Réagissent, s''identifient |\n| **Pratique** | 60 min | Distribue les graines, guide l''exercice | Construisent LEUR budget en graines |\n| **Conceptualisation** | 20 min | Pose la question : « Qu''avez-vous découvert ? » | Formulent : « On dépense plus qu''on ne gagne pendant 7 mois » |\n| **Action** | 15 min | « Que comptez-vous faire d''ici la prochaine session ? » | S''engagent : « Je vais calculer mon budget avec ma femme » |"},
  {"type": "embed", "title": "Notebook live : planifier un cycle de 12 sessions", "code": "sessions = [\n    (1, \"Mois 1 - S1\", \"D ou vient et ou va l argent ?\", \"Cailloux entrants/sortants\"),\n    (2, \"Mois 1 - S2\", \"Mon budget familial en graines\", \"12 tas + graines maïs/haricots\"),\n    (3, \"Mois 1 - S3\", \"L epargne : ou je garde mon argent ?\", \"Classement des formes d epargne\"),\n    (4, \"Mois 1 - S4\", \"La tontine et l AVEC\", \"Simulation tontine en cercle\"),\n    (5, \"Mois 2 - S5\", \"Combien me coute mon champ ?\", \"Calcul cout de production\"),\n    (6, \"Mois 2 - S6\", \"Planifier ma campagne\", \"Corde des saisons + tresorerie\"),\n    (7, \"Mois 2 - S7\", \"Le credit : opportunite ou piege ?\", \"Jeu de role 3 preteurs\"),\n    (8, \"Mois 2 - S8\", \"Vendre au bon moment\", \"Courbe des prix au sol\"),\n    (9, \"Mois 3 - S9\", \"Les risques et le fonds d urgence\", \"3 boites / methode enveloppes\"),\n    (10, \"Mois 3 - S10\", \"Structurer ma session de formation\", \"Preparer une fiche APCA\"),\n    (11, \"Mois 3 - S11\", \"Animer ma premiere session (pratique)\", \"Chaque stagiaire anime 20 min\"),\n    (12, \"Mois 3 - S12\", \"Bilan et plan d action communautaire\", \"Engagement collectif du village\"),\n]\nprint(\"PARCOURS DE FORMATION — 12 sessions sur 3 mois\")\nprint(f\"{'#':>2} {'Periode':<14} {'Theme':<42} {'Activite pratique'}\")\nprint(\"-\" * 95)\nfor n, p, t, a in sessions:\n    print(f\"{n:>2} {p:<14} {t:<42} {a}\")\nprint(f\"\\nTotal : {len(sessions)} sessions x 2h = 24 heures de formation\")\n"},
  {"type": "callout", "variant": "tip", "title": "La fiche de session : votre outil indispensable", "content": "Pour CHAQUE session, préparez une fiche A4 recto-verso : objectif, matériel nécessaire, déroulement APCA minute par minute, questions de facilitation, et la SEULE chose à retenir. Cette fiche, vous la donnez aux formateurs que vous formez. C''est l''outil de démultiplication."},
  {"type": "quiz", "question": "Dans le cycle APCA, à quel moment le formateur parle-t-il le plus ?", "opts": ["Pendant l''Accroche", "Pendant la Pratique", "Nulle part — le formateur parle 20% du temps maximum, le groupe fait 80%", "Pendant la Conceptualisation"], "ans": 2}
]}'::jsonb
FROM sms_courses WHERE code = 'TOF-FIN-01';

-- ── Leçon 11 : Pratique — animer sa première session ──
INSERT INTO sms_lessons (course_id, title, type, points, order_index, content)
SELECT id, 'Pratique supervisée : animez votre première session', 'notebook', 25, 11,
'{"cells": [
  {"type": "md", "content": "## C''est à vous de jouer !\n\n**Durée** : 3h | **Format** : chaque stagiaire anime 20 minutes devant le groupe\n\n### Consignes\n\n1. Choisissez UN thème parmi les sessions 1 à 9\n2. Préparez votre fiche APCA (leçon 10)\n3. Animez 20 minutes devant vos co-stagiaires qui jouent le rôle des paysans\n4. Le groupe et le superviseur donnent un retour constructif\n\n### Grille d''observation (pour le superviseur et les pairs)\n\n| Critère | 1 (à améliorer) | 2 (correct) | 3 (excellent) |\n|---|---|---|---|\n| Le formateur pose des questions avant d''expliquer | Fait un cours magistral | Pose quelques questions | Le groupe parle 80% du temps |\n| Utilisation du matériel concret (cailloux, dessins) | Tout à l''oral | Un support utilisé | Activité pratique bien menée |\n| Langage simple, pas de jargon | Termes techniques | Quelques mots compliqués | Langue locale + français simple |\n| Gestion du temps (respect du cycle APCA) | Pas de structure | APCA approximatif | 4 phases bien gérées |\n| Bienveillance (pas de jugement, valorise les savoirs) | Corrige / impose | Neutre | Valorise activement les réponses |"},
  {"type": "callout", "variant": "real", "title": "L''erreur la plus fréquente", "content": "90% des stagiaires formateurs font la MÊME erreur lors de leur première animation : ils parlent trop et ne laissent pas assez le groupe réfléchir. C''est normal — on a tous été formés par le modèle scolaire (le maître parle, l''élève écoute). L''andragogie, c''est le contraire. Il faut PRATIQUER pour désapprendre."},
  {"type": "md", "content": "## Le feedback constructif : la méthode sandwich\n\nAprès chaque animation de 20 minutes :\n\n1. **Pain du haut** : « Ce que tu as bien fait... » (toujours commencer par le positif)\n2. **Garniture** : « Ce que tu pourrais améliorer... » (un seul point, le plus important)\n3. **Pain du bas** : « Ce que j''ai particulièrement apprécié... » (finir sur du positif)\n\nLe superviseur donne son feedback EN DERNIER, après les pairs. Pourquoi ? Pour que les stagiaires apprennent aussi à s''évaluer entre eux."},
  {"type": "embed", "title": "Notebook live : auto-évaluation du formateur", "code": "print(\"AUTO-EVALUATION DU FORMATEUR — apres votre session\")\nprint(\"=\" * 50)\ncriteres = [\n    \"J ai laisse le groupe parler au moins 80% du temps\",\n    \"J ai utilise du materiel concret (cailloux, dessins)\",\n    \"J ai commence par un probleme vecu (Accroche)\",\n    \"J ai pose des questions au lieu d expliquer\",\n    \"J ai laisse le groupe formuler la lecon (Conceptualisation)\",\n    \"J ai propose un engagement concret (Action)\",\n    \"J ai parle en langue accessible (pas de jargon)\",\n    \"J ai respecte le temps (2h maximum)\",\n]\nprint(\"\\nRepondez OUI ou NON a chaque critere :\\n\")\nscore = 0\nfor i, c in enumerate(criteres, 1):\n    # Simulation : score aleatoire pour l''exemple\n    reponse = \"OUI\" if i % 3 != 0 else \"NON\"\n    score += 1 if reponse == \"OUI\" else 0\n    print(f\"  {i}. {c}\")\n    print(f\"     -> {reponse}\")\n\nprint(f\"\\nScore : {score}/{len(criteres)}\")\nif score >= 7: print(\"Excellent ! Vous etes pret(e) a animer au village.\")\nelif score >= 5: print(\"Bien ! Travaillez les points faibles avant le terrain.\")\nelse: print(\"Refaites une session d entrainement avec un pair.\")\n"},
  {"type": "quiz", "question": "Lors du feedback à un stagiaire, par quoi commencez-vous ?", "opts": ["Par les erreurs à corriger", "Par ce qu''il a bien fait (méthode sandwich)", "Par une note chiffrée", "Par un silence"], "ans": 1}
]}'::jsonb
FROM sms_courses WHERE code = 'TOF-FIN-01';

-- ── Leçon 12 : Capstone — Plan d'action communautaire ──
INSERT INTO sms_lessons (course_id, title, type, points, order_index, content)
SELECT id, 'Capstone : votre plan d''action communautaire', 'notebook', 30, 12,
'{"cells": [
  {"type": "md", "content": "## Bilan et engagement : que va changer ce parcours ?\n\n**Durée** : 3h | **Format** : atelier collectif de planification\n\n### Ce que vous maîtrisez maintenant\n\nEn 3 mois, vous avez appris à :\n\n- ✅ Adopter la posture de facilitateur (pas de professeur)\n- ✅ Animer le diagnostic financier participatif (cailloux, graines)\n- ✅ Accompagner la construction du budget familial\n- ✅ Expliquer l''épargne, la tontine, l''AVEC\n- ✅ Calculer le coût de production avec les paysans\n- ✅ Planifier la campagne agricole (corde des saisons)\n- ✅ Comparer les options de crédit (jeu de rôle)\n- ✅ Enseigner les stratégies de commercialisation\n- ✅ Mettre en place un fonds d''urgence (méthode des enveloppes)\n- ✅ Structurer une session APCA et animer avec confiance"},
  {"type": "callout", "variant": "real", "title": "L''impact réel de cette formation", "content": "Au Bénin, un programme similaire de formation de formateurs en gestion financière paysanne a touché 45 formateurs, qui ont chacun formé 4 groupes de 25 paysans. Résultat : 4 500 ménages touchés, avec en moyenne +35% d''épargne et -40% de recours au crédit du commerçant après 1 an. Vous êtes le premier maillon de cette chaîne."},
  {"type": "md", "content": "## Activité finale : le plan d''action communautaire\n\n### Chaque formateur remplit son plan :\n\n1. **Où** : dans quel(s) village(s) allez-vous intervenir ?\n2. **Quand** : dates des 12 sessions (un calendrier réaliste)\n3. **Qui** : combien de groupes ? Combien de participants par groupe ?\n4. **Comment** : quel matériel avez-vous besoin ? (graines, cordes, images)\n5. **Suivi** : comment mesurerez-vous le changement ? (avant/après)\n\n### Le tableau de suivi\n\n| Indicateur | Avant formation | Après 6 mois | Objectif |\n|---|---|---|---|\n| % de ménages avec un budget | à mesurer | à mesurer | 60% |\n| Épargne moyenne mensuelle | à mesurer | à mesurer | +30% |\n| % utilisant le crédit commerçant | à mesurer | à mesurer | -50% |\n| Nb de tontines/AVEC actives | à compter | à compter | +3 |"},
  {"type": "embed", "title": "Notebook live : projeter l''impact de votre formation", "code": "print(\"PROJECTION D IMPACT — Votre plan de formation\")\nprint(\"=\" * 55)\n\nnb_formateurs = 1  # vous\ngroupes_par_formateur = 4\npaysans_par_groupe = 25\ntotal_paysans = nb_formateurs * groupes_par_formateur * paysans_par_groupe\npersonnes_par_menage = 7  # moyenne Afrique de l Ouest\ntotal_beneficiaires = total_paysans * personnes_par_menage\n\nprint(f\"Formateurs formes       : {nb_formateurs}\")\nprint(f\"Groupes a former        : {groupes_par_formateur}\")\nprint(f\"Paysans par groupe      : {paysans_par_groupe}\")\nprint(f\"Total paysans touches   : {total_paysans}\")\nprint(f\"Beneficiaires indirects : {total_beneficiaires} personnes\")\nprint(f\"                          (menages de {personnes_par_menage} personnes)\")\n\nprint(f\"\\n--- Si chaque paysan forme a son tour forme 2 voisins ---\")\neffet_boule = total_paysans * 2\nprint(f\"Effet boule de neige    : +{effet_boule} paysans supplementaires\")\nprint(f\"Impact total possible   : {(total_paysans + effet_boule) * personnes_par_menage:,} personnes\")\n\nprint(f\"\\n--- Impact financier estime ---\")\nepargne_moyenne = 16000  # FCFA/mois\nepargne_annuelle = epargne_moyenne * 12 * total_paysans\nprint(f\"Si chaque paysan epargne {epargne_moyenne:,} FCFA/mois\")\nprint(f\"Epargne collective annuelle : {epargne_annuelle:,} FCFA\")\nprint(f\"Soit {epargne_annuelle // 655:,} euros mobilises dans la communaute\")\n"},
  {"type": "md", "content": "## La certification\n\nPour obtenir votre **attestation de Formateur en Gestion Financière Paysanne**, vous devez :\n\n1. ✅ Avoir suivi les 12 sessions (présence)\n2. ✅ Avoir réussi les quiz (score ≥ 70%)\n3. ✅ Avoir animé une session supervisée (leçon 11, note ≥ 2/3 sur chaque critère)\n4. ✅ Avoir remis votre plan d''action communautaire\n\nDemandez votre attestation depuis votre tableau de bord étudiant !"},
  {"type": "callout", "variant": "real", "title": "Vous êtes maintenant formateur", "content": "Vous faites partie d''un réseau de formateurs ruraux en gestion financière. Votre mission : aller dans les villages, écouter les paysans, et les accompagner vers une meilleure maîtrise de leur argent. Pas avec des théories, mais avec des cailloux, des graines, des histoires vraies et beaucoup d''écoute. Bon terrain !"},
  {"type": "resource", "title": "Kit du formateur rural (outils GRAAP)", "url": "https://www.yourcentre.org/", "provider": "GRAAP / Réseau andragogique", "desc": "Guides visuels, images grand format, et méthodologies d''animation participative pour formateurs en milieu rural africain."},
  {"type": "resource", "title": "Guide VSLA — Village Savings and Loan Associations", "url": "https://www.vsla.net/", "provider": "CARE International", "desc": "Le guide méthodologique complet pour créer et accompagner des groupes d''épargne villageois (AVEC/VSLA). Gratuit, traduit en français."},
  {"type": "quiz", "question": "Vous avez formé 4 groupes de 25 paysans. Chacun forme 2 voisins. Combien de personnes sont touchées au total (paysans directs + effet boule de neige) ?", "opts": ["100 paysans", "200 paysans", "300 paysans (100 directs + 200 par effet boule de neige)", "500 paysans"], "ans": 2}
]}'::jsonb
FROM sms_courses WHERE code = 'TOF-FIN-01';
